=== rubenfgr/job-cr4vegas-almacen-v2/bin/main/es/rfgr/cr4vegas/modelo/postgresql/conexion/xsd/jdbc.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="parametros">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bdoficina" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="bdalmacen" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bdoficina" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ip" type="xs:string"/>
				<xs:element name="port" type="xs:string"/>
				<xs:element name="db" type="xs:string"/>
				<xs:element name="driver" type="xs:string"/>
				<xs:element name="user" type="xs:string"/>
				<xs:element name="pass" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bdalmacen" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ip" type="xs:string"/>
				<xs:element name="port" type="xs:string"/>
				<xs:element name="db" type="xs:string"/>
				<xs:element name="driver" type="xs:string"/>
				<xs:element name="user" type="xs:string"/>
				<xs:element name="pass" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
<!--
	<xs:element name="codigo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[A-Z]{3}-[A-Z]{1,2}-[0-9]{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:simpleType name="t_limite_caracteres">
		<xs:restriction base="xs:string">
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="t_precio">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>
-->
</xs:schema>

=== rubenfgr/job-cr4vegas-almacen-v2/src/main/resources/es/rfgr/cr4vegas/modelo/postgresql/conexion/datos.xml
<?xml version="1.0" encoding="utf-8"?>
<parametros xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="xsd/jdbc.xsd">

	<bdoficina>
		<ip>192.168.1.10</ip>
		<port>5432</port>
		<db>4vegas</db>
		<driver>org.postgresql.Driver</driver>
		<user>vegas1</user>
		<pass>modchip2</pass>
	</bdoficina>
	
	<bdalmacen>
		<ip>192.168.1.236</ip>
		<port>5432</port>
		<db>cr4vegas</db>
		<driver>org.postgresql.Driver</driver>
		<user>postgres</user>
		<pass>rfgr87dev</pass>
	</bdalmacen>
	
</parametros>
